"""Emit animations_gen.c / animations_gen.h from baked clips."""

from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass
class ClipSpec:
    enum_name: str
    c_symbol: str
    frame_count: int
    delay_ms: int
    packed: bytes


def _sanitize_symbol(clip_id: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", clip_id.lower())
    if s and s[0].isdigit():
        s = "anim_" + s
    return s


def clip_id_to_enum(clip_id: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", clip_id)
    name = "_".join(p for p in parts if p).upper()
    return "ANIM_" + name if name else "ANIM_UNKNOWN"


def emit_header(clips: list[ClipSpec], playlists: dict[str, list[str]], clip_id_to_enum_map: dict[str, str]) -> str:
    enum_lines = "\n".join(f"    {c.enum_name}," for c in clips)
    enum_lines += "\n    ANIM_COUNT,"

    lines = [
        "/* Auto-generated by tools/flip_anim/build_animations.py — do not edit. */",
        "#ifndef ANIMATIONS_GEN_H",
        "#define ANIMATIONS_GEN_H",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "typedef enum {",
        enum_lines,
        "} anim_id_t;",
        "",
        "typedef struct {",
        "    const uint8_t *frames;",
        "    uint16_t frame_count;",
        "    uint16_t delay_ms;",
        "} anim_clip_t;",
        "",
        "const anim_clip_t *anim_clip_get(anim_id_t id);",
        "",
    ]

    for playlist_name, ids in playlists.items():
        sym = playlist_name.upper() + "_PLAYLIST"
        entries = ", ".join(clip_id_to_enum_map[i] for i in ids)
        lines.append(f"extern const anim_id_t {sym}[];")
        lines.append(f"extern const size_t {sym}_LEN;")
        lines.append("")

    lines.extend(["#endif /* ANIMATIONS_GEN_H */", ""])
    return "\n".join(lines)


def emit_source(
    clips: list[ClipSpec],
    playlists: dict[str, list[str]],
    clip_id_to_enum_map: dict[str, str],
    bytes_per_frame: int,
) -> str:
    parts = [
        "/* Auto-generated by tools/flip_anim/build_animations.py — do not edit. */",
        '#include "animations_gen.h"',
        "",
    ]

    for clip in clips:
        hex_lines = []
        data = clip.packed
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            hex_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
        parts.append(f"static const uint8_t anim_data_{clip.c_symbol}[] = {{")
        parts.append(",\n".join(hex_lines))
        parts.append("};")
        parts.append("")
        parts.append(f"static const anim_clip_t clip_{clip.c_symbol} = {{")
        parts.append(f"    .frames = anim_data_{clip.c_symbol},")
        parts.append(f"    .frame_count = {clip.frame_count},")
        parts.append(f"    .delay_ms = {clip.delay_ms},")
        parts.append("};")
        parts.append("")

    parts.append("static const anim_clip_t *const clip_table[ANIM_COUNT] = {")
    for clip in clips:
        parts.append(f"    [{clip.enum_name}] = &clip_{clip.c_symbol},")
    parts.append("};")
    parts.append("")

    parts.append("const anim_clip_t *anim_clip_get(anim_id_t id)")
    parts.append("{")
    parts.append("    if ((unsigned)id >= (unsigned)ANIM_COUNT) {")
    parts.append("        return NULL;")
    parts.append("    }")
    parts.append("    return clip_table[id];")
    parts.append("}")
    parts.append("")

    for playlist_name, ids in playlists.items():
        sym = playlist_name.upper() + "_PLAYLIST"
        entries = ", ".join(clip_id_to_enum_map[i] for i in ids)
        parts.append(f"const anim_id_t {sym}[] = {{ {entries} }};")
        parts.append(f"const size_t {sym}_LEN = sizeof({sym}) / sizeof({sym}[0]);")
        parts.append("")

    return "\n".join(parts) + "\n"
